# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen/mainPy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(897, 640)
        MainWindow.setStyleSheet("background-color: rgb(167, 108, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.admintext = QtWidgets.QTextBrowser(self.centralwidget)
        self.admintext.setGeometry(QtCore.QRect(120, 30, 641, 261))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.admintext.setFont(font)
        self.admintext.setStyleSheet("background-color: rgb(192, 44, 255);")
        self.admintext.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextSelectableByMouse)
        self.admintext.setObjectName("admintext")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 510, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(470, 510, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.time.setFont(font)
        self.time.setText("")
        self.time.setObjectName("time")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 540, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.word = QtWidgets.QLabel(self.centralwidget)
        self.word.setGeometry(QtCore.QRect(470, 550, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.word.setFont(font)
        self.word.setText("")
        self.word.setObjectName("word")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(360, 470, 171, 31))
        self.start.setObjectName("start")
        self.usertext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.usertext.setGeometry(QtCore.QRect(120, 310, 641, 131))
        self.usertext.setStyleSheet("background-color: rgb(192, 44, 255);")
        self.usertext.setPlainText("")
        self.usertext.setObjectName("usertext")
        self.start_2 = QtWidgets.QPushButton(self.centralwidget)
        self.start_2.setGeometry(QtCore.QRect(360, 590, 171, 31))
        self.start_2.setObjectName("start_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.admintext.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">A </span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Your Time :"))
        self.label_2.setText(_translate("MainWindow", "Correct Word: "))
        self.start.setText(_translate("MainWindow", "Start Typing"))
        self.start_2.setText(_translate("MainWindow", "End Typing"))
