# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen/page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui1_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(871, 754)
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 7, 7, 255), stop:0.55 rgba(235, 71, 71, 255), stop:0.98 rgba(110, 110, 110, 255), stop:1 rgba(0, 0, 0, 0))\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.liveCurr = QtWidgets.QLabel(self.centralwidget)
        self.liveCurr.setGeometry(QtCore.QRect(10, 390, 861, 361))
        self.liveCurr.setText("")
        self.liveCurr.setObjectName("liveCurr")
        self.loginCustomer = QtWidgets.QPushButton(self.centralwidget)
        self.loginCustomer.setGeometry(QtCore.QRect(550, 210, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.loginCustomer.setFont(font)
        self.loginCustomer.setObjectName("loginCustomer")
        self.loginAdmin = QtWidgets.QPushButton(self.centralwidget)
        self.loginAdmin.setGeometry(QtCore.QRect(550, 320, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.loginAdmin.setFont(font)
        self.loginAdmin.setObjectName("loginAdmin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginCustomer.setText(_translate("MainWindow", "Login as Customer"))
        self.loginAdmin.setText(_translate("MainWindow", "Login as Admin"))
